### ISSUE TITLE
Deskripsi tidak terlihat dengan jelas saat mode dark mode dihidupkan

### ISSUE THREAD

**Issue by ainunns** [ia-toki/tlx#109]
Pada soal [ini](https://tlx.toki.id/courses/basic/chapters/13/problems/G) , deskripsi soal yang berada pada tabel tidak tampak saat mode dark mode dinyalakan. tetapi deskripsi tampak dengan baik ketika mode light mode dinyalakan

Berikut adalah screenshot ketika mode dark mode dinyalakan
![image](https://user-images.githubusercontent.com/58164571/168461169-64689bb7-4f7b-4f9c-b568-8a04c6db724f.png)

Berikut adalah screenshot ketika mode light mode dinyalakan
![image](https://user-images.githubusercontent.com/58164571/168461174-1bf0aa05-67a5-459b-a335-5023e9eeedf3.png)

**Comment by fushar** [comment]
Sudah diperbaiki, terima kasih!
